### ISSUE TITLE
Option to provide css in config

### ISSUE THREAD

**Issue by swapagarwal** [matusnovak/gitbook-plugin-insert-logo#2]
I want to have custom css added in the image div. I'm open to adding this feature in this plugin itself, or forking it to something like `gitbook-plugin-insert-styled-logo`. Let me know your thoughts on this! 😄

**Comment by matusnovak** [comment]
Hi @swapagarwal 

The div has class of "book-logo" which should be able to be referenced in a custom GitBook css files, such as:

```css
Somewhere in styles/website.css

.book-logo > img {
  background: red;
}
```

But yeah, adding the CSS directly into the configuration file would be easier. 

If you have a working solution, I am more than happy to accept a pull request. Alternatively, just copy paste the code here and I will add it. If not, give me one day and I will come up with something.

**Comment by swapagarwal** [comment]
@matusnovak Thanks for the quick reply!
Adding in `styles/website.css` would definitely work but config would be cleaner. 👍 
I'll send you a PR soon! 😄
