### ISSUE TITLE
Logo disappears after first nested chapter

### ISSUE THREAD

**Issue by smythp** [matusnovak/gitbook-plugin-insert-logo#4]
Hi, thanks for the plugin!

I've noticed that the logo disappears after the first page that is nested in the ToC. Might be base the HTML is slightly different and it doesn't know where to insert? Wonder if you've tested with a book that has nested chapters.

**Comment by matusnovak** [comment]
Hello @smythp 

I have not tested it with ToC. It's very likely it is due to the HTML. Were there any JavaScript errors in the console? 

Also, the plugin uses simple `$('.book-summary').children().eq(0).before("<span>Logo in inserted here</span>)` to add the logo into the page. If you open the developer tools, you can give it a try and test if the sample code works. If it does not, the HTML structure is different.

**Comment by smythp** [comment]
I had thought that was the issue but it was actually a simpler problem and not related to your plugin. The reason the logo disappeared is that the link in the config is relative to the individual markdown file, not to the root project directory. So it worked for my files that were in the root project folder that had access to the image but not to markdown files that were in their own folders. This is a GitBook issue, though, not an issue with your plugin. They need add a templating variable that binds to the root project directory like Jekyll has. Also, I don't think templating works in the JSON config file right now anyway.  But I've worked around the issue by providing an absolute link to the logo hosted online. Thanks for responding, and thanks for the plugin!

**Comment by matusnovak** [comment]
@smythp 

I also had similar issues with using relative paths. I will update the README in case someone has a similar issue. 

You could also use base64 for your logo. For example, in the config file:
```
"pluginsConfig": {
    "insert-logo": {
        "url": "data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7"
    }
}
```

_The image is a tiny gif taken from here: https://css-tricks.com/data-uris/_

I am closing this issue as resolved. In case you find another problem, feel free to reopen or create a new issue.
